/* this testing file was generated by AI */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "duck_string.h"

static int fail(const char *name);
static int same_sign(int left, int right);
static int bytes_equal(const void *left, const void *right, size_t n);
static int test_strlen(void);
static int test_strcpy(void);
static int test_strncpy(void);
static int test_strcmp(void);
static int test_strncmp(void);
static int test_strchr(void);
static int test_strstr(void);
static int test_memcpy(void);
static int test_memmove(void);
static int test_memset(void);

static int fail(const char *name) {
    fprintf(stderr, "FAIL: %s\n", name);
    return 1;
}

static int same_sign(int left, int right) {
    return (left < 0 && right < 0) ||
           (left == 0 && right == 0) ||
           (left > 0 && right > 0);
}

static int bytes_equal(const void *left, const void *right, size_t n) {
    return memcmp(left, right, n) == 0;
}

static int test_strlen(void) {
    const char *strings[5];
    size_t i;
    int failures;

    strings[0] = "";
    strings[1] = "a";
    strings[2] = "hello world";
    strings[3] = "embedded\0tail";
    strings[4] = "0123456789";

    failures = 0;
    for (i = 0; i < 5; ++i) {
        if (duck_strlen(strings[i]) != strlen(strings[i])) {
            failures += fail("duck_strlen");
        }
    }

    return failures;
}

static int test_strcpy(void) {
    const char *sources[3];
    char actual[32];
    char expected[32];
    size_t i;
    int failures;

    sources[0] = "";
    sources[1] = "hello";
    sources[2] = "a longer string with spaces";

    failures = 0;
    for (i = 0; i < 3; ++i) {
        (void) memset(actual, 0x5A, sizeof actual);
        (void) memset(expected, 0x5A, sizeof expected);
        if (duck_strcpy(actual, sources[i]) != actual) {
            failures += fail("duck_strcpy return value");
        }
        (void) strcpy(expected, sources[i]);
        if (strcmp(actual, expected) != 0) {
            failures += fail("duck_strcpy contents");
        }
    }

    return failures;
}

static int test_strncpy(void) {
    const char *sources[3];
    size_t limits[5];
    char actual[24];
    char expected[24];
    size_t source_index;
    size_t limit_index;
    int failures;

    sources[0] = "";
    sources[1] = "abc";
    sources[2] = "hello world";
    limits[0] = 0;
    limits[1] = 1;
    limits[2] = 3;
    limits[3] = 10;
    limits[4] = 24;

    failures = 0;
    for (source_index = 0; source_index < 3; ++source_index) {
        for (limit_index = 0; limit_index < 5; ++limit_index) {
            (void) memset(actual, 0x5A, sizeof actual);
            (void) memset(expected, 0x5A, sizeof expected);
            if (duck_strncpy(actual, sources[source_index],
                             limits[limit_index]) != actual) {
                failures += fail("duck_strncpy return value");
            }
            (void) strncpy(expected, sources[source_index], limits[limit_index]);
            if (!bytes_equal(actual, expected, sizeof actual)) {
                failures += fail("duck_strncpy contents");
            }
        }
    }

    return failures;
}

static int test_strcmp(void) {
    const char *pairs[6][2];
    size_t i;
    int failures;

    pairs[0][0] = "";
    pairs[0][1] = "";
    pairs[1][0] = "abc";
    pairs[1][1] = "abc";
    pairs[2][0] = "abc";
    pairs[2][1] = "abd";
    pairs[3][0] = "abc";
    pairs[3][1] = "ab";
    pairs[4][0] = "ab";
    pairs[4][1] = "abc";
    pairs[5][0] = "x\001y";
    pairs[5][1] = "x\002y";

    failures = 0;
    for (i = 0; i < 6; ++i) {
        if (!same_sign(duck_strcmp(pairs[i][0], pairs[i][1]),
                       strcmp(pairs[i][0], pairs[i][1]))) {
            failures += fail("duck_strcmp");
        }
    }

    return failures;
}

static int test_strncmp(void) {
    const char *pairs[5][2];
    size_t pair_index;
    size_t n;
    int failures;

    pairs[0][0] = "abc";
    pairs[0][1] = "abc";
    pairs[1][0] = "abc";
    pairs[1][1] = "abd";
    pairs[2][0] = "abc";
    pairs[2][1] = "ab";
    pairs[3][0] = "ab";
    pairs[3][1] = "abc";
    pairs[4][0] = "x\001y";
    pairs[4][1] = "x\002y";

    failures = 0;
    for (pair_index = 0; pair_index < 5; ++pair_index) {
        for (n = 0; n <= 4; ++n) {
            if (!same_sign(duck_strncmp(pairs[pair_index][0],
                                        pairs[pair_index][1], n),
                           strncmp(pairs[pair_index][0],
                                   pairs[pair_index][1], n))) {
                failures += fail("duck_strncmp");
            }
        }
    }

    return failures;
}

static int test_strchr(void) {
    const char *strings[3];
    size_t string_index;
    size_t char_index;
    char *actual;
    char *expected;
    int failures;

    strings[0] = "";
    strings[1] = "abcabc";
    strings[2] = "a\001b";

    failures = 0;
    for (string_index = 0; string_index < 3; ++string_index) {
        for (char_index = 0;
             char_index <= strlen(strings[string_index]);
             ++char_index) {
            actual = duck_strchr(strings[string_index],
                                 (unsigned char) strings[string_index][char_index]);
            expected = strchr(strings[string_index],
                              (unsigned char) strings[string_index][char_index]);
            if (actual != expected) {
                failures += fail("duck_strchr present");
            }
        }
        actual = duck_strchr(strings[string_index], '\001');
        expected = strchr(strings[string_index], '\001');
        if (actual != expected) {
            failures += fail("duck_strchr absent");
        }
        actual = duck_strchr(strings[string_index], 0);
        expected = strchr(strings[string_index], 0);
        if (actual != expected) {
            failures += fail("duck_strchr terminator");
        }
    }

    return failures;
}

static int test_strstr(void) {
    const char *haystacks[3];
    const char *needles[6];
    size_t haystack_index;
    size_t needle_index;
    char *actual;
    char *expected;
    int failures;

    haystacks[0] = "";
    haystacks[1] = "abracadabra";
    haystacks[2] = "mississippi";
    needles[0] = "";
    needles[1] = "a";
    needles[2] = "bra";
    needles[3] = "cad";
    needles[4] = "xyz";
    needles[5] = "issi";

    failures = 0;
    for (haystack_index = 0; haystack_index < 3; ++haystack_index) {
        for (needle_index = 0; needle_index < 6; ++needle_index) {
            actual = duck_strstr(haystacks[haystack_index],
                                 needles[needle_index]);
            expected = strstr(haystacks[haystack_index],
                              needles[needle_index]);
            if (actual != expected) {
                failures += fail("duck_strstr");
            }
        }
    }

    return failures;
}

static int test_memcpy(void) {
    unsigned char source[16];
    unsigned char actual[16];
    unsigned char expected[16];
    size_t i;
    size_t n;
    int failures;

    failures = 0;
    for (n = 0; n <= 16; ++n) {
        for (i = 0; i < 16; ++i) {
            source[i] = (unsigned char) (i * 3 + 1);
            actual[i] = 0;
            expected[i] = 0;
        }
        if (duck_memcpy(actual, source, n) != actual) {
            failures += fail("duck_memcpy return value");
        }
        (void) memcpy(expected, source, n);
        if (!bytes_equal(actual, expected, 16)) {
            failures += fail("duck_memcpy contents");
        }
    }

    return failures;
}

static int test_memmove(void)
{
    unsigned char pattern[24];
    unsigned char actual[24];
    unsigned char expected[24];
    size_t i;
    size_t dest_offset;
    size_t src_offset;
    size_t n;
    int failures;

    for (i = 0; i < 24; ++i) {
        pattern[i] = (unsigned char) (i + 1);
    }

    failures = 0;
    for (dest_offset = 0; dest_offset < 16; dest_offset += 4) {
        for (src_offset = 0; src_offset < 16; src_offset += 3) {
            for (n = 0; n <= 8; n += 2) {
                (void) memcpy(actual, pattern, 24);
                (void) memcpy(expected, pattern, 24);
                if (duck_memmove(actual + dest_offset,
                                 actual + src_offset, n) != actual + dest_offset) {
                    failures += fail("duck_memmove return value");
                }
                (void) memmove(expected + dest_offset,
                               expected + src_offset, n);
                if (!bytes_equal(actual, expected, 24)) {
                    failures += fail("duck_memmove contents");
                }
            }
        }
    }

    return failures;
}

static int test_memset(void)
{
    unsigned char actual[16];
    unsigned char expected[16];
    int values[4];
    size_t value_index;
    size_t n;
    int failures;

    values[0] = 0;
    values[1] = 'A';
    values[2] = 0xFF;
    values[3] = 0x7F;

    failures = 0;
    for (value_index = 0; value_index < 4; ++value_index) {
        for (n = 0; n <= 16; ++n) {
            (void) memset(actual, 0x5A, 16);
            (void) memset(expected, 0x5A, 16);
            if (duck_memset(actual, values[value_index], n) != actual) {
                failures += fail("duck_memset return value");
            }
            (void) memset(expected, values[value_index], n);
            if (!bytes_equal(actual, expected, 16)) {
                failures += fail("duck_memset contents");
            }
        }
    }

    return failures;
}

int main(void)
{
    int failures;

    failures = 0;
    failures += test_strlen();
    failures += test_strcpy();
    failures += test_strncpy();
    failures += test_strcmp();
    failures += test_strncmp();
    failures += test_strchr();
    failures += test_strstr();
    failures += test_memcpy();
    failures += test_memmove();
    failures += test_memset();

    if (failures == 0) {
        printf("duckstring: all tests passed\n");
        return EXIT_SUCCESS;
    }

    fprintf(stderr, "duckstring: %d test(s) failed\n", failures);
    return EXIT_FAILURE;
}